version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.4.0

workflows:
  setup:
    jobs:
      - fetch-and-continue

jobs:
  fetch-and-continue:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Download shared config (cache-busting)
          command: |
            wget \
              --header="Cache-Control: no-cache" \
              --header="Pragma: no-cache" \
              "https://raw.githubusercontent.com/dof-dss/webdev-ci/development/shared-config.yml?nocache=$(date +%s)" \
              -O shared-config.yml

      - run:
          name: Combine shared jobs and local workflows
          command: |
            # Remove the 'version: 2.1' from workflows config (since it's in shared config).
            tail -n +2 .circleci/workflow-config.yml > workflows-only.yml
            # Concatenate shared jobs+commands with repo workflows
            cat shared-config.yml workflows-only.yml > full-config.yml

      - continuation/continue:
          configuration_path: full-config.yml
          parameters: |
            {
              "php_version": "8.3",
              "node_version": "14",
              "drupal_core_version": "10.4",
              "custom_code_dirs": "${PROJECT_ROOT}/web/themes/origins",
              "deprecated_code_dirs": "${PROJECT_ROOT}/web/themes/origins",
              "supporting_repo_dependent_packages": "mglaman/drupal-check"
            }
