version: 2.1

workflows:
  static_analysis:
    jobs:
      - theme_install:
          php_version: << pipeline.parameters.php_version >>
      - theme_lint:
          php_version: << pipeline.parameters.php_version >>
          requires:
            - theme_install
      - theme_build_assets:
          php_version: << pipeline.parameters.php_version >>
          requires:
            - theme_install
      - supporting_repo_coding_standards:
          php_version: << pipeline.parameters.php_version >>
      - supporting_repo_deprecated_code:
          php_version: << pipeline.parameters.php_version >>
          custom_code_dirs: << pipeline.parameters.custom_code_dirs >>
          drupal_core_version: << pipeline.parameters.drupal_core_version >>
          supporting_repo_dependent_packages: << pipeline.parameters.supporting_repo_dependent_packages >>
      - supporting_repo_disallowed_functions:
          php_version: << pipeline.parameters.php_version >>
          custom_code_dirs: << pipeline.parameters.custom_code_dirs >>
          drupal_core_version: << pipeline.parameters.drupal_core_version >>
